import "@/designSystem/globals.scss";
import type { Metadata } from "next";
import { Geist, Lavishly_Yours, PT_Serif } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const ptSerif = PT_Serif({
	variable: "--font-pt-serif",
	subsets: ["latin"],
	weight: "400",
});

const cedarville = Lavishly_Yours({
	variable: "--font-edarville-cursive",
	subsets: ["latin"],
	weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/icon?family=Material+Icons"
				/>
			</head>
			<body
				className={`${geistSans.variable} ${ptSerif.variable} ${cedarville.variable}`}
			>
				<AppRouterCacheProvider>{children}</AppRouterCacheProvider>
			</body>
		</html>
	);
}
